version: '2'

volumes:
  nextcloud:
  app:
  config:
  data:
  theme:

services:
  app:  
    image: nextcloud
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
      - app:/var/www/html/custom_apps
      - config:/var/www/html/config
      - data:/var/www/html/data
      - theme:/var/www/html/themes/mlvx
    restart: always
