apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.15.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: nextcloud-app
  name: nextcloud-app
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nextcloud-app
    spec:
      containers:
      - image: nextcloud
        name: nextcloud-app
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html
          name: nextcloud
        - mountPath: /var/www/html/custom-apps
          name: nextcloud-apps
        - mountPath: /var/www/html/config
          name: nextcloud-config
        - mountPath: /var/www/html/data
          name: nextcloud-data
        - mountPath: /var/www/html/themes/mlvx
          name: nextcloud-theme
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "chown -R www-data:www-data /var/www/html/data"]
      restartPolicy: Always
      volumes:
      - name: nextcloud
        persistentVolumeClaim:
          claimName: nextcloud
      - name: nextcloud-apps
        persistentVolumeClaim:
          claimName: nextcloud-apps
      - name: nextcloud-config
        persistentVolumeClaim:
          claimName: nextcloud-config
      - name: nextcloud-data
        persistentVolumeClaim:
          claimName: nextcloud-data
      - name: nextcloud-theme
        persistentVolumeClaim:
          claimName: nextcloud-theme
status: {}
