apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nextcloud
  name: nextcloud
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
